### ISSUE TITLE
Example command line for Nextera Paired-End data?

### ISSUE THREAD

**Issue by tseemann** [relipmoc/skewer#16]
Could you please provide the command line for Nextera paired-end reads?  
(Not mate pair)

**Comment by relipmoc** [comment]
$ skewer -x CGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG -y GACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT -m any -t 10 raw_R1.fastq.gz raw_R2.fastq.gz -o data

**Comment by tseemann** [comment]
Thanks @relipmoc !

**Comment by ATpoint** [comment]
Hello, I do not think that the provided sequences are fully appropriate for Nextera. It will remove most of the sequencing adapters, but not the transposase adapter itself, which has the sequence GTATAAGAGACAG and appears right upstream of the actual insert sequence that you are interested in:

**Simplified:**
5'-[5' adapter]-[GTATAAGAGACAG transposase adapter]-[sequence of interest]-[3' adapter]-3'

That means when the sequencing-by-synthesis starts from 3' adapter, the GTATAAGAGACAG will be sequenced before those sequences listed above. So just offering CTGTCTCTTATA for -x and -y should remove the entire "contamination".
-x and -y are the same in this case, as the Nextera transposase is loaded with two different sequences, sharing the same "core" (GTATAAGAGACAG) but different 5' overhangs for the primers. See the Illumina adapter sequences sheet for details:

http://support.illumina.com/content/dam/illumina-support/documents/documentation/chemistry_documentation/experiment-design/illumina-adapter-sequences_1000000002694-01.pdf
