### ISSUE TITLE
Set custom path for output

### ISSUE THREAD

**Issue by royfrancis** [relipmoc/skewer#43]
Is it possible to set a different path for the output files other than the current working directory?

```sh
skewer \
-x "AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC" \
-y "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTA" \
-m pe \
-u \
-n \
-k 6 \
-l 20 \
-o sampleA \
sampleA_1.fq.gz sampleA_2.fq.gz
```

Since the documentation says `-o` is a base name, 
`-o, --output <str>   Base name of output file; ('<reads>.trimmed')`

I was wondering if adding a path prefix would work?
`-o /home/custompath/sampleA`

**Comment by ATpoint** [comment]
Of course. Standard rules of the command line apply, -o /path/to/directory/sampleA
