### ISSUE TITLE
won't compile on mac os x

### ISSUE THREAD

**Issue by dakl** [relipmoc/skewer#8]
Cloning from github and running make on OS X (10.10) gives this error: 

```
$ make
g++ -c -O2 src/main.cpp -o src/main.o
src/main.cpp:350:17: error: use of undeclared identifier 'CLOCK_MONOTONIC'
                clock_gettime(CLOCK_MONOTONIC, &tpstart);
                              ^
src/main.cpp:353:17: error: use of undeclared identifier 'CLOCK_MONOTONIC'
                clock_gettime(CLOCK_MONOTONIC, &tpend);
                              ^
2 errors generated.
make: *** [src/main.o] Error 1
```

https://github.com/SIPp/sipp/issues/81 might be useful, since they seem to have solved this for another tool. My C or C++ isn't sharp enough to fix this. 

thanks

**Comment by wltrimbl** [comment]
I think I've fixed this with PR#9.

**Comment by roryk** [comment]
Pretty sure relipmoc has abandonded this, would you be up for taking over as the fork we use, @wltrimbl?

**Comment by roryk** [comment]
Oh nm, activity last month-- it has been months between activity though. Would you be down for a group of us helping to maintain this @relipmoc?

**Comment by relipmoc** [comment]
Thank you for using skewer! Now skewer can be compiled on OS X. Please check out the codes.
